#! /usr/bin/env perl
use strict;
use warnings;

local $/;
my $text = <>;

$text =~ s(<a href=['"](.*?)['"]>(.*?)<\/a>)(\n[$2]($1))simg;
$text =~ s(\[url=['"]?(.*?)['"]?\](.*?)\[\/url\])(\n[$2]($1))simg;

$text =~ s(<img src=['"](.*?)['"] />)(\n![]($1))simg;

$text =~ s(<em>(.*?)</em>)(_$1_)simg;
$text =~ s(<b>(.*?)</b>)(**$1**)simg;
$text =~ s(\[b\](.*?)\[/b\])(**$1**)simg;

$text =~ s(<h1>(.*?)</h1>)(## $1)simg;
$text =~ s(<h2>(.*?)</h2>)(### $1)simg;
$text =~ s(<h3>(.*?)</h3>)(#### $1)simg;
$text =~ s(<h4>(.*?)</h4>)(##### $1)simg;

while ($text =~ m(<blockquote>(.*?)</blockquote>)sim) {
  (my $content = $1) =~ s(\n)()g;
  $text =~ s(<blockquote>(.*?)</blockquote>)(\n> $content\n)sim;
}

while ($text =~ m(\[quote\](.*?)\[/quote\])sim) {
  (my $content = $1) =~ s(\n)()g;
  $text =~ s(\[quote\](.*?)\[/quote\])(\n> $content\n)sim;
}

$text =~ s(http://blog.koehntopp.info/wp-content)()simg;
$text =~ s(<p>)()simg;
$text =~ s(</p>)()simg;
$text =~ s(<br />)()simg;
$text =~ s(&nbsp;)( )simg;

$text =~ s(author: isotopp)(author-id: isotopp
feature-img: assets/img/background/rijksmuseum.jpg)sim;
$text =~ s(^author_login:.*?\n)()sim;
$text =~ s(^author_email:.*?\n)()sim;
$text =~ s(^wordpress_id:.*?\n)()sim;
$text =~ s(^wordpress_url:.*?\n)()sim;
$text =~ s(^date_gmt:.*?\n)()sim;
$text =~ s(^tags.*?\n)()sim;
$text =~ s(^categories:)(tags:)sim;

print "$text";
